name: Pactum JS Test

on: [push, pull_request]

jobs:
  testClassPactumJs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setando o Node.js versão 20
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Instalando as dependências do projeto
      run: npm install

    - name: Executando os testes e2e com Pactum JS
      run: npm run e2e
